# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  push: 
  schedule:
     - cron: '* * * * *'
  # Lines below let you run workflow manually and on each commit
  # workflow_dispatch:
  jobs:
    build: Make metrics SVG
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org  (for organization related metrics)
          #  - read:user (for user related data)
          #  - repo      (optional, if you want to include private repositories)
          # token: ${{ secrets.METRICS_TOKEN }}

          # Options
          # user: atosinu
          template: classic
          base: ""
          config_display: large
          config_padding: 0, 8 + 11%
          plugin_people: yes
          plugin_people_limit: 24
          plugin_people_size: 120
          plugin_people_types: followers, following
